---
# For use with pre-commit.
# See usage instructions at https://pre-commit.com
- repo: local
  hooks:
  - id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: system
    types: [file, yaml]
