---
# Adapted from
# - https://github.com/drhelius/travis-ansible-demo/blob/master/.travis.yml
# - https://github.com/geerlingguy/ansible-role-docker/blob/master/.travis.yml
language: python
services:
  - docker

env:
  global:
    - ANSIBLE_ROLE: slurm

  matrix:
    - name: Ubuntu-18.04
      env:
        - DOCKER_IMAGE=marvelnccr/ubuntu-docker-base
        - DOCKER_IMAGE_VERSION=2.2
    - name: Ubuntu-16.04
      env:
        - DOCKER_IMAGE=marvelnccr/ubuntu-docker-base
        - DOCKER_IMAGE_VERSION=1.1

install:
  - pip install -r requirements.txt

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ANSIBLE_ROLE marvel-nccr.$ANSIBLE_ROLE
  - cd marvel-nccr.$ANSIBLE_ROLE

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
