- name: set hostname to {{ slurm_hostname }}
  become: true
  hostname:
    name: "{{ slurm_hostname }}"
  # hostname works inconsistently on Docker containers: https://github.com/ansible/ansible/issues/19681
  # it works for Ubuntu 18.04, but fails locally and on GH actions for 16.04
  # raising: Failed to create bus connection: No such file or directory
  when: not (cloud_platform is defined and cloud_platform == 'docker' and ansible_os_family == 'Debian' and ansible_distribution_major_version == '16')

# Yaml requires escaping backslashes in double quotes but not in single quotes
# This works for docker, both locally and on travis
- name: Set hostname in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^(172\\.17\\.[0-9]+\\.[0-9]+)\\s+.*$"
    line: "\\1 {{ slurm_hostname }}"
    backrefs: true
    unsafe_writes: true
  when: slurm_set_hostname or (cloud_platform is defined and cloud_platform == 'docker')
