---
# Adds a system service that forces the hostname on startup
# Note: This is necessary when preparing images for cloud platforms like AWS

- name: copy init.d template
  become: True
  become_user: "{{ root_user }}"
  template:
   src: "fix-hostname"
   dest: "/etc/init.d/"
   mode: 0755

- name: enable service forcing hostname to {{ slurm_hostname }}
  become: True
  become_user: "{{ root_user }}"
  shell: update-rc.d fix-hostname defaults
  args:
    creates: "/etc/rc5.d/S??fix-hostname"

- name: start service to set the hostname
  become: True
  become_user: "{{ root_user }}"
  service:
      name: fix-hostname
      state: started

## should will trigger if-up.d script defined in scheduler
#- name: restart networking service
#  become: True
#  become_user: "{{ root_user }}"
#  service:
#      name: networking
#      state: restarted
