- hosts: all

  pre_tasks:

  - name: Update apt cache.
    become: true
    apt:
      update_cache: yes
      cache_valid_time: 600
    when: ansible_os_family == 'Debian'

  - name: Install dbus
    apt:
      name: "dbus"
      state: present
    when: ansible_os_family == 'Debian'

  # - name: Just force systemd to reread configs (2.4 and above)
  #   systemd:
  #     daemon_reload: yes

  # - name: Enable dbus
  #   service:
  #     name: "dbus.service"
  #     enabled: yes
  #   when: ansible_os_family == 'Debian'

  - name: Enable dbus
    systemd:
      name: dbus.service
      # state: started
      enabled: yes

  vars:
  - run_tests: true
  - cloud_platform: docker
  - slurm_hostname_service: true
  - slurm_resources_service: true

  roles:
  - role: marvel-nccr.slurm
