dependency:
  name: galaxy
#   requirements_file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
- name: instance
  image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
  # by default the container will initialise with systemd as PID1
  command: ${MOLECULE_DOCKER_COMMAND:-""}
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  cgroupns_mode: host
  privileged: true
  pre_build_image: true
  env:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
provisioner:
  name: ansible
  # log: true  # use for debugging
  playbooks:
    converge: converge.yml
    verify: verify.yml
  config_options:
    defaults:
      # nicer stdout printing
      stdout_callback: default
      result_format: yaml
      bin_ansible_callbacks: true
      # add timing to tasks
      callback_whitelist: profile_tasks
