- name: Verify
  hosts: all

  tasks:
  - name: Get slurm version
    ansible.builtin.command: sinfo -V
    changed_when: false
    register: slurm_version

  - name: Display slurm version
    ansible.builtin.debug:
      var: slurm_version.stdout

  # normally only started on init
  - name: Check starting slurm-resources
    become: true
    ansible.builtin.systemd:
      name: slurm-resources.service
      state: started

  - name: Check running slurm-resources script
    ansible.builtin.command: slurm-resources -e restart_slurm=true -e slurm_max_cpus=2
    changed_when: false
