on:
  push:
    branches: [master]
    tags:
    - 'v*'
  pull_request:

jobs:

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: pre-commit/action@v2.0.0

  molecule:

    strategy:
      fail-fast: false
      matrix:
        # ubuntu-16.04, ubuntu-18.04
        docker-version: ["1.1", "2.2"]

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        path: marvel-nccr.slurm

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip --version

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run molecule
      run: molecule test
      env:
        DOCKER_IMAGE: marvelnccr/ubuntu-docker-base
        DOCKER_IMAGE_VERSION: ${{ docker-version }}
